/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF('/island2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.bush1_palm_lambert_0.geometry}
        material={materials.palm_lambert}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick24_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-5.95, 65.581, 9.982]}
        rotation={[0, 1.221, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass1_grass_lambert_0.geometry}
        material={materials.grass_lambert}
        position={[-4.548, 64.661, -1.829]}
        rotation={[0, 0.724, 0]}
        scale={[0.303, 1.331, 0.867]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass10_grass_lambert_0.geometry}
        material={materials.grass_lambert}
        position={[-26.531, 63.153, 13.917]}
        rotation={[0, 0.724, 0]}
        scale={[0.303, 1.331, 0.867]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass2_grass_lambert_0.geometry}
        material={materials.grass_lambert}
        position={[5.48, 63.072, 14.981]}
        rotation={[0, 0.724, 0]}
        scale={[0.303, 1.331, 0.825]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass3_grass_lambert_0.geometry}
        material={materials.grass_lambert}
        position={[-10.226, 63.698, 13.36]}
        rotation={[-3.137, 0.582, 3.093]}
        scale={[0.833, 1.331, 1.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.grass4_grass_lambert_0.geometry}
        material={materials.grass_lambert}
        position={[-2.847, 64.061, 29.77]}
        rotation={[-Math.PI, 1.018, -Math.PI]}
        scale={[0.303, 1.331, 1.331]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.column1_column_lambert_0.geometry}
        material={materials.column_lambert}
        position={[3.447, 66.736, 14.995]}
        rotation={[0, 1.027, 0]}
        scale={0.553}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.column2_column_lambert_0.geometry}
        material={materials.column_lambert}
        position={[-5.243, 66.736, 9.705]}
        rotation={[-Math.PI, 0.712, -Math.PI]}
        scale={0.553}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick1_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[0.644, 65.581, 12.837]}
        rotation={[0, -0.349, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick10_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.425, 65.581, 17.197]}
        rotation={[3.107, -0.416, 3.132]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick11_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.164, 65.581, 17.628]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick12_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.863, 65.489, 18.126]}
        rotation={[Math.PI, -0.44, Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick13_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.575, 65.581, 18.602]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick14_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.269, 65.581, 19.11]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick15_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.007, 65.581, 19.541]}
        rotation={[0, 1.221, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick16_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[0.706, 65.489, 20.039]}
        rotation={[Math.PI, -0.44, Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick17_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[0.419, 65.581, 20.515]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick18_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-2.101, 65.581, 11.23]}
        rotation={[0, 1.027, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick19_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-2.575, 65.581, 10.848]}
        rotation={[0, -0.349, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick2_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.16, 65.581, 13.149]}
        rotation={[0, 1.027, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick20_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-2.935, 65.489, 10.673]}
        rotation={[-Math.PI, 1.131, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick21_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-3.506, 65.581, 10.38]}
        rotation={[0, 1.027, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick22_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-3.88, 65.581, 10.104]}
        rotation={[3.064, 1.153, -3.066]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick23_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-4.404, 65.581, 9.837]}
        rotation={[0, 1.027, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick25_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-6.252, 65.489, 10.48]}
        rotation={[Math.PI, -0.44, Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick26_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-6.539, 65.581, 10.956]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick27_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-6.821, 65.581, 11.423]}
        rotation={[3.107, -0.416, 3.132]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick28_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-7.082, 65.581, 11.854]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick29_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-7.383, 65.489, 12.352]}
        rotation={[Math.PI, -0.44, Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick3_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.592, 65.581, 13.41]}
        rotation={[3.064, 1.153, -3.066]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick30_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-7.671, 65.581, 12.828]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick31_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-7.978, 65.581, 13.336]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick32_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-8.239, 65.581, 13.767]}
        rotation={[0, 1.221, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick33_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-8.54, 65.489, 14.265]}
        rotation={[Math.PI, -0.44, Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick34_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-8.828, 65.581, 14.741]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick4_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.058, 65.581, 13.692]}
        rotation={[0, 1.027, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick5_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.534, 65.489, 13.98]}
        rotation={[-Math.PI, 1.131, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick6_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[3.032, 65.581, 14.281]}
        rotation={[0, -0.349, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick7_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[3.296, 65.581, 15.756]}
        rotation={[0, 1.221, 0]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick8_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.995, 65.489, 16.254]}
        rotation={[Math.PI, -0.44, Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.fence_stick9_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.707, 65.581, 16.73]}
        rotation={[-Math.PI, 0.544, -Math.PI]}
        scale={0.282}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.house_base_House_lambert_0.geometry}
        material={materials.House_lambert}
        position={[-4.692, 63.919, 18.227]}
        rotation={[0, 1.027, 0]}
        scale={0.794}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.house_body_House_lambert_0.geometry}
        material={materials.House_lambert}
        position={[-6.415, 67.264, 21.312]}
        rotation={[0, 1.027, 0]}
        scale={0.553}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar1_pillar_lambert_0.geometry}
        material={materials.pillar_lambert}
        position={[2.271, 62.686, 15.339]}
        rotation={[0, 1.027, 0]}
        scale={0.896}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar2_pillar_lambert_0.geometry}
        material={materials.pillar_lambert}
        position={[-5.348, 62.686, 10.733]}
        rotation={[0, 1.027, 0]}
        scale={0.896}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar3_pillar_lambert_0.geometry}
        material={materials.pillar_lambert}
        position={[-11.868, 62.686, 21.528]}
        rotation={[0, 1.027, 0]}
        scale={0.896}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pillar4_pillar_lambert_0.geometry}
        material={materials.pillar_lambert}
        position={[-4.254, 62.686, 26.132]}
        rotation={[0, 1.027, 0]}
        scale={0.896}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar10_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-0.068, 63.629, 8.859]}
        rotation={[0, 0.661, 0]}
        scale={[0.244, 0.261, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar11_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-0.761, 64.647, 9.943]}
        rotation={[1.074, -0.281, -1.099]}
        scale={[4.187, 0.697, 0.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar4_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[2.163, 63.629, 10.207]}
        rotation={[0, -0.349, 0]}
        scale={[0.244, 0.261, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar5_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.5, 64.647, 11.309]}
        rotation={[1.074, -0.281, -1.099]}
        scale={[4.187, 0.697, 0.46]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar6_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[1.605, 64.37, 11.13]}
        rotation={[Math.PI, -0.87, Math.PI]}
        scale={[0.244, 0.261, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar7_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[0.942, 65.094, 12.227]}
        rotation={[Math.PI, -0.207, Math.PI]}
        scale={[0.244, 0.261, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar8_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-1.289, 65.094, 10.878]}
        rotation={[0, 0.661, 0]}
        scale={[0.244, 0.261, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pollar9_fence_lambert_0.geometry}
        material={materials.fence_lambert}
        position={[-0.626, 64.37, 9.781]}
        rotation={[0, 0.661, 0]}
        scale={[0.244, 0.261, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.roof_roof_lambert_0.geometry}
        material={materials.roof_lambert}
        position={[-6.415, 74.503, 21.26]}
        rotation={[0, 1.027, 0]}
        scale={0.685}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stairs_base_House_lambert_0.geometry}
        material={materials.House_lambert}
        position={[-0.121, 63.604, 11.459]}
        rotation={[0, 1.027, 0]}
        scale={0.553}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.island_body1_island1_lambert_0.geometry}
        material={materials.island1_lambert}
        position={[0, 28.876, -1.823]}
        scale={62.453}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm1_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[25.917, 56.554, 33.658]}
        rotation={[0, 1.515, 0]}
        scale={1.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm2_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[-16.945, 52.836, 27.639]}
        rotation={[0, 0, 0.084]}
        scale={1.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm3_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[-35.214, 50.334, 43.127]}
        rotation={[0, -0.355, 0.062]}
        scale={1.425}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm5_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[-22.409, 47.214, 7.376]}
        rotation={[0, -0.355, 0.062]}
        scale={1.425}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm6_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[-1.211, 49.607, -8.08]}
        rotation={[0, 0, 0.084]}
        scale={1.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm7_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[38.722, 53.434, -2.093]}
        rotation={[0, 1.515, 0]}
        scale={1.173}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.palm8_palm_lambert_0.geometry}
        material={materials.palm_lambert}
        position={[4.611, 55.42, -8.986]}
        rotation={[-2.374, 1.446, 2.339]}
        scale={1.425}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.pCube29_grass_lambert_0.geometry}
        material={materials.grass_lambert}
        position={[-11.852, 62.62, -15.204]}
        rotation={[0, 0.724, -0.25]}
        scale={[0.303, 1.331, 0.571]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone1_stone_lambert_0.geometry}
        material={materials.stone_lambert}
        position={[20.468, 62.888, 8.818]}
        scale={[0.128, 0.128, 0.218]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone2_stone_lambert_0.geometry}
        material={materials.stone_lambert}
        position={[26.43, 59.557, -20.656]}
        scale={[0.128, 0.128, 0.218]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.stone3_stone_lambert_0.geometry}
        material={materials.stone_lambert}
        position={[-13.591, 64.201, -14.129]}
        scale={[0.138, 0.128, 0.163]}
      />
    </group>
  )
}

useGLTF.preload('/island2.glb')
