/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model3(props) {
  const { nodes, materials } = useGLTF('/island3.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[-45788.672, -34649.5, 0]}>
          <group position={[-0.004, -0.004, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_3.geometry}
              material={materials['rastMat.001']}
              position={[-0.004, -0.004, 0]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/island3.glb')
