/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model1(props) {
  const { nodes, materials } = useGLTF('/island1.glb')
  return (
    <group {...props} dispose={null}>
      <group
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.021}
        userData={{ name: 'Collada visual scene group' }}>
        <group position={[28.271, 7.942, -32.298]} scale={4.076} userData={{ name: 'Cube_001' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material011'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.011' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW1-material'].geometry}
            material={materials.material_1}
            userData={{ name: 'YW1-material' }}
          />
        </group>
        <group position={[85.822, -8.607, 10.83]} scale={1.854} userData={{ name: 'Cube_001_001' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material034'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.034' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material006'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE1-material011'].geometry}
            material={materials['material_7.001']}
            userData={{ name: 'WE1-material.011' }}
          />
        </group>
        <group
          position={[116.321, 22.931, 10.83]}
          rotation={[0, 0, -0.73]}
          scale={1.854}
          userData={{ name: 'Cube_002' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material033'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.033' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material005'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE1-material010'].geometry}
            material={materials['material_7.001']}
            userData={{ name: 'WE1-material.010' }}
          />
        </group>
        <group position={[124.192, -61.408, -4.952]} scale={10.434} userData={{ name: 'Cube_003' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material005'].geometry}
            material={materials['material_4.001']}
            userData={{ name: 'BN-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN2-material'].geometry}
            material={materials.material_9}
            userData={{ name: 'BN2-material' }}
          />
        </group>
        <group
          position={[-118.18, -16.75, 7.735]}
          rotation={[0, 0, -2.811]}
          scale={1.854}
          userData={{ name: 'Cube_004' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material032'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.032' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material004'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE1-material009'].geometry}
            material={materials['material_7.001']}
            userData={{ name: 'WE1-material.009' }}
          />
        </group>
        <group
          position={[-28.313, 7.237, 40.723]}
          rotation={[0, 0, -0.541]}
          scale={0.123}
          userData={{ name: 'Cube_005' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material003'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['G2-material010'].geometry}
            material={materials.material_5}
            userData={{ name: 'G2-material.010' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material012'].geometry}
            material={materials['material_14.001']}
            userData={{ name: 'YW2-material.012' }}
          />
        </group>
        <group
          position={[13.284, 47.831, 37.411]}
          rotation={[0, 0, -1.949]}
          scale={0.123}
          userData={{ name: 'Cube_006' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material002'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['G2-material009'].geometry}
            material={materials.material_5}
            userData={{ name: 'G2-material.009' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material011'].geometry}
            material={materials['material_14.001']}
            userData={{ name: 'YW2-material.011' }}
          />
        </group>
        <group
          position={[22.367, 46.851, 36.641]}
          rotation={[0, 0, -2.089]}
          scale={0.123}
          userData={{ name: 'Cube_007' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material001'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['G2-material008'].geometry}
            material={materials.material_5}
            userData={{ name: 'G2-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material010'].geometry}
            material={materials['material_14.001']}
            userData={{ name: 'YW2-material.010' }}
          />
        </group>
        <group
          position={[-16.034, -39.732, 36.128]}
          rotation={[0, 0, 0.497]}
          scale={0.123}
          userData={{ name: 'Cube_008' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['G2-material007'].geometry}
            material={materials.material_5}
            userData={{ name: 'G2-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material009'].geometry}
            material={materials['material_14.001']}
            userData={{ name: 'YW2-material.009' }}
          />
        </group>
        <group
          position={[10.547, 126.386, -2.504]}
          rotation={[0, 0, 0.837]}
          scale={1.854}
          userData={{ name: 'Cube_014' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material031'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.031' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material003'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE1-material005'].geometry}
            material={materials['material_7.001']}
            userData={{ name: 'WE1-material.005' }}
          />
        </group>
        <group
          position={[-31.449, 146.739, -2.504]}
          rotation={[0, 0, 1.808]}
          scale={1.854}
          userData={{ name: 'Cube_014_001' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material001'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material001'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE1-material002'].geometry}
            material={materials['material_7.001']}
            userData={{ name: 'WE1-material.002' }}
          />
        </group>
        <group
          position={[71.048, -69.318, 18.152]}
          rotation={[0, 0, -0.459]}
          scale={1.854}
          userData={{ name: 'Cube_014_002' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE1-material001'].geometry}
            material={materials['material_7.001']}
            userData={{ name: 'WE1-material.001' }}
          />
        </group>
        <group
          position={[-30.231, 8.044, 42.747]}
          scale={1.006}
          userData={{ name: 'Cylinder_000' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material004'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material007'].geometry}
            material={materials['material_3.001']}
            userData={{ name: 'GN1-material.007' }}
          />
        </group>
        <group
          position={[24.305, 47.26, 57.479]}
          rotation={[-3.006, -0.088, 0.999]}
          scale={0.824}
          userData={{ name: 'Cylinder_002' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material006'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material013'].geometry}
            material={materials['material_3.001']}
            userData={{ name: 'GN1-material.013' }}
          />
        </group>
        <group position={[-127.862, -83.651, -7.422]} scale={0.871} userData={{ name: 'Plane' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material008'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material030'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.030' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material008'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.008' }}
          />
        </group>
        <group
          position={[-26.402, -44.448, 57.932]}
          rotation={[0.596, 0.362, 2.147]}
          scale={2.363}
          userData={{ name: 'Plane_001' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material007'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['G2-material030'].geometry}
            material={materials.material_5}
            userData={{ name: 'G2-material.030' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material014'].geometry}
            material={materials['material_3.001']}
            userData={{ name: 'GN1-material.014' }}
          />
        </group>
        <group
          position={[-8.061, -48.68, 57.932]}
          rotation={[-0.658, 0.208, -1.736]}
          scale={2.435}
          userData={{ name: 'Plane_002' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BN-material008'].geometry}
            material={materials.material_4}
            userData={{ name: 'BN-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['G2-material031'].geometry}
            material={materials.material_5}
            userData={{ name: 'G2-material.031' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material015'].geometry}
            material={materials['material_3.001']}
            userData={{ name: 'GN1-material.015' }}
          />
        </group>
        <group
          position={[-22.248, -37.371, 40.167]}
          rotation={[0.184, 0.084, -0.889]}
          scale={0.072}
          userData={{ name: 'Plane_004' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material011'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.011' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material010'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.010' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material010'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.010' }}
          />
        </group>
        <group
          position={[-17.279, -44.943, 37.616]}
          rotation={[0.313, -0.01, -2.429]}
          scale={0.065}
          userData={{ name: 'Plane_005' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material010'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.010' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material009'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.009' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material009'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.009' }}
          />
        </group>
        <group
          position={[24.724, 45.592, 39.215]}
          rotation={[0.04, 0.046, -2.331]}
          scale={0.077}
          userData={{ name: 'Plane_006' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material009'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.009' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material008'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material008'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.008' }}
          />
        </group>
        <group
          position={[24.675, 51.638, 38.075]}
          rotation={[-0.182, 0, 0]}
          scale={0.063}
          userData={{ name: 'Plane_007' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material008'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material007'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material007'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.007' }}
          />
        </group>
        <group
          position={[-13.048, -36.614, 38.106]}
          rotation={[-0.016, -0.016, 0.006]}
          scale={0.062}
          userData={{ name: 'Plane_008' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material012'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.012' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material011'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.011' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material011'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.011' }}
          />
        </group>
        <group
          position={[128.505, 6.01, 7.465]}
          rotation={[0, 0, -0.286]}
          scale={0.334}
          userData={{ name: 'Plane_009' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material015'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.015' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material015'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.015' }}
          />
        </group>
        <group
          position={[13.705, 53.352, 38.22]}
          rotation={[-0.052, 0, -0.009]}
          scale={0.046}
          userData={{ name: 'Plane_010' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material' }}
          />
        </group>
        <group
          position={[99.425, -50.955, -0.123]}
          rotation={[0, 0, -0.286]}
          scale={0.334}
          userData={{ name: 'Plane_012' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material014'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.014' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material014'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.014' }}
          />
        </group>
        <group
          position={[134.082, -43.386, -2.001]}
          rotation={[0, 0, -0.286]}
          scale={0.334}
          userData={{ name: 'Plane_014' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material013'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.013' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material013'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.013' }}
          />
        </group>
        <group
          position={[-122.829, -107.225, -8.446]}
          rotation={[0, 0, -0.286]}
          scale={0.285}
          userData={{ name: 'Plane_017' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material012'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.012' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material012'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.012' }}
          />
        </group>
        <group
          position={[-123.65, -89.532, -7.891]}
          rotation={[0, 0, -1.841]}
          scale={0.322}
          userData={{ name: 'Plane_018' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material011'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.011' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material011'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.011' }}
          />
        </group>
        <group
          position={[-103.792, 58.626, 7.465]}
          rotation={[0, 0, -1.841]}
          scale={0.334}
          userData={{ name: 'Plane_021' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material010'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.010' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material010'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.010' }}
          />
        </group>
        <group
          position={[-115.454, 77.794, 0.928]}
          rotation={[0, 0, -2.545]}
          scale={0.334}
          userData={{ name: 'Plane_022' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material009'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.009' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material009'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.009' }}
          />
        </group>
        <group
          position={[-141.082, 139.369, -11.396]}
          rotation={[0, 0, -2.545]}
          scale={0.334}
          userData={{ name: 'Plane_022_001' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material' }}
          />
        </group>
        <group
          position={[-75.793, 92.86, 0.928]}
          rotation={[0, 0, 2.431]}
          scale={0.334}
          userData={{ name: 'Plane_027' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material008'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material008'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.008' }}
          />
        </group>
        <group
          position={[-91.251, 76.597, 7.465]}
          rotation={[0, 0, 3.135]}
          scale={0.334}
          userData={{ name: 'Plane_028' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material007'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material007'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.007' }}
          />
        </group>
        <group
          position={[58.796, -41.404, 1.758]}
          rotation={[0, 0, 3.135]}
          scale={0.334}
          userData={{ name: 'Plane_031' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material006'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material006'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.006' }}
          />
        </group>
        <group
          position={[74.254, -25.142, -4.779]}
          rotation={[0, 0, 2.431]}
          scale={0.334}
          userData={{ name: 'Plane_032' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material005'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material005'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.005' }}
          />
        </group>
        <group
          position={[-32.009, 5.998, 42.776]}
          rotation={[0.173, 0.011, -1.752]}
          scale={0.081}
          userData={{ name: 'Plane_038' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material006'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material006'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material006'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.006' }}
          />
        </group>
        <group
          position={[-29.129, 3.982, 43.144]}
          rotation={[-0.073, -0.013, 0.175]}
          scale={0.081}
          userData={{ name: 'Plane_039' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material005'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material005'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material005'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.005' }}
          />
        </group>
        <group
          position={[-23.314, 23.186, 41.726]}
          rotation={[0.024, 0.038, -0.631]}
          scale={0.081}
          userData={{ name: 'Plane_040' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material004'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material004'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material004'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.004' }}
          />
        </group>
        <group
          position={[-27.119, 18.211, 42.157]}
          rotation={[-0.03, -0.048, 2.18]}
          scale={0.081}
          userData={{ name: 'Plane_041' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material003'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material003'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material003'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.003' }}
          />
        </group>
        <group
          position={[-30.023, 22.582, 40.762]}
          rotation={[-0.131, -0.131, -2.778]}
          scale={0.081}
          userData={{ name: 'Plane_043' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material002'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material002'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material002'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.002' }}
          />
        </group>
        <group
          position={[-31.062, 8.495, 41.703]}
          rotation={[0.111, -0.131, -0.806]}
          scale={0.041}
          userData={{ name: 'Plane_044' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN1-material001'].geometry}
            material={materials.material_3}
            userData={{ name: 'GN1-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN3-material001'].geometry}
            material={materials.material_10}
            userData={{ name: 'GN3-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GN4-material001'].geometry}
            material={materials['Lamp.001']}
            userData={{ name: 'GN4-material.001' }}
          />
        </group>
        <group
          position={[-136.54, 99.763, -5.187]}
          rotation={[0, 0, -2.545]}
          scale={0.334}
          userData={{ name: 'Plane_045' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material004'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material004'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.004' }}
          />
        </group>
        <group
          position={[-111.919, 129.813, -9.457]}
          rotation={[0, 0, -2.545]}
          scale={0.334}
          userData={{ name: 'Plane_046' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material003'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material003'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.003' }}
          />
        </group>
        <group
          position={[95.858, -72.871, 1.758]}
          rotation={[0, 0, 1.617]}
          scale={0.334}
          userData={{ name: 'Plane_048' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material002'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material002'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.002' }}
          />
        </group>
        <group
          position={[120.211, -77.513, -1.324]}
          rotation={[0, 0, -1.371]}
          scale={0.334}
          userData={{ name: 'Plane_051' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP1-material001'].geometry}
            material={materials.material_12}
            userData={{ name: 'LP1-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['LP2-material001'].geometry}
            material={materials.material_13}
            userData={{ name: 'LP2-material.001' }}
          />
        </group>
        <group position={[128.904, 38.877, 11.188]} scale={0.871} userData={{ name: 'Plane_052' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material029'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.029' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material010'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.010' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material010'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.010' }}
          />
        </group>
        <group
          position={[132.313, 43.296, 11.188]}
          rotation={[0, 0, 0.419]}
          scale={0.871}
          userData={{ name: 'Plane_053' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material027'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.027' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material009'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.009' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material009'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.009' }}
          />
        </group>
        <group position={[-98.488, 112.491, -3.359]} scale={0.871} userData={{ name: 'Plane_054' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material028'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.028' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material008'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material008'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.008' }}
          />
        </group>
        <group
          position={[124.105, 42.665, 11.188]}
          rotation={[0, 0, -0.223]}
          scale={0.871}
          userData={{ name: 'Plane_055' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material026'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.026' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material008'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material008'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.008' }}
          />
        </group>
        <group
          position={[125.242, 36.73, 11.188]}
          rotation={[0, 0, -0.223]}
          scale={0.871}
          userData={{ name: 'Plane_056' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material025'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.025' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material007'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material007'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.007' }}
          />
        </group>
        <group
          position={[132.313, 36.225, 11.188]}
          rotation={[0, 0, 0.303]}
          scale={0.871}
          userData={{ name: 'Plane_057' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material024'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.024' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material006'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material006'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.006' }}
          />
        </group>
        <group
          position={[129.409, 32.311, 11.188]}
          rotation={[0, 0, 0.087]}
          scale={0.871}
          userData={{ name: 'Plane_058' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material023'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.023' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material005'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material005'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.005' }}
          />
        </group>
        <group
          position={[127.009, 31.174, 11.188]}
          rotation={[0, 0, 0.087]}
          scale={0.871}
          userData={{ name: 'Plane_059' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material022'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.022' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material004'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material004'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.004' }}
          />
        </group>
        <group
          position={[136.182, 46.31, 11]}
          rotation={[0, 0, -2.674]}
          scale={0.871}
          userData={{ name: 'Plane_060' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material007'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material021'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.021' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material007'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.007' }}
          />
        </group>
        <group position={[87.968, -60.312, 5.995]} scale={0.871} userData={{ name: 'Plane_061' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material020'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.020' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material007'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material007'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.007' }}
          />
        </group>
        <group
          position={[91.329, -59.508, 5.995]}
          rotation={[0, 0, -0.889]}
          scale={0.871}
          userData={{ name: 'Plane_062' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material019'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.019' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material006'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material006'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.006' }}
          />
        </group>
        <group
          position={[86.506, -55.635, 5.995]}
          rotation={[0, 0, -1.231]}
          scale={0.871}
          userData={{ name: 'Plane_063' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material018'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.018' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material005'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material005'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.005' }}
          />
        </group>
        <group
          position={[89.868, -56.95, 5.995]}
          rotation={[0, 0, -0.891]}
          scale={0.871}
          userData={{ name: 'Plane_064' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material017'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.017' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material004'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material004'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.004' }}
          />
        </group>
        <group
          position={[84.606, -60.02, 5.995]}
          rotation={[0, 0, -0.328]}
          scale={0.871}
          userData={{ name: 'Plane_065' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material016'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.016' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material003'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material003'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.003' }}
          />
        </group>
        <group
          position={[-132.334, -97.681, -7.422]}
          rotation={[0, 0, 1.337]}
          scale={0.871}
          userData={{ name: 'Plane_066' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material006'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material015'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.015' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material006'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.006' }}
          />
        </group>
        <group
          position={[-116.989, -98.032, -7.422]}
          rotation={[0, 0, -2.108]}
          scale={0.871}
          userData={{ name: 'Plane_067' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material005'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material014'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.014' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material005'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.005' }}
          />
        </group>
        <group
          position={[-121.11, -86.107, -7.422]}
          rotation={[0, 0, -0.84]}
          scale={0.871}
          userData={{ name: 'Plane_068' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material004'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material013'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.013' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material004'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.004' }}
          />
        </group>
        <group
          position={[-130.844, -88.562, -7.422]}
          rotation={[0, 0, 1.144]}
          scale={0.871}
          userData={{ name: 'Plane_069' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material003'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material012'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.012' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material003'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.003' }}
          />
        </group>
        <group
          position={[-127.862, -95.051, -7.422]}
          rotation={[0, 0, -0.413]}
          scale={0.871}
          userData={{ name: 'Plane_070' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material002'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material011'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.011' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material002'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.002' }}
          />
        </group>
        <group
          position={[-113.535, 100.257, -7.422]}
          rotation={[0, 0, -0.413]}
          scale={0.871}
          userData={{ name: 'Plane_071' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material001'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material010'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.010' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material001'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material.001' }}
          />
        </group>
        <group
          position={[-136.809, 121.349, -7.422]}
          rotation={[0, 0, -2.237]}
          scale={0.871}
          userData={{ name: 'Plane_072' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['B2-material'].geometry}
            material={materials.material_15}
            userData={{ name: 'B2-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material009'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.009' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['YW2-material'].geometry}
            material={materials.material_14}
            userData={{ name: 'YW2-material' }}
          />
        </group>
        <group
          position={[-141.581, 124.492, -3.359]}
          rotation={[0, 0, -0.391]}
          scale={0.871}
          userData={{ name: 'Plane_073' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material008'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.008' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material002'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material002'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.002' }}
          />
        </group>
        <group
          position={[-130.671, 90.853, -3.359]}
          rotation={[0, 0, -0.754]}
          scale={0.871}
          userData={{ name: 'Plane_074' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material007'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.007' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material001'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material001'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material.001' }}
          />
        </group>
        <group
          position={[-152.127, 99.581, -3.359]}
          rotation={[0, 0, -0.754]}
          scale={0.871}
          userData={{ name: 'Plane_075' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material006'].geometry}
            material={materials.material_8}
            userData={{ name: 'BK1-material.006' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK-material'].geometry}
            material={materials.material_17}
            userData={{ name: 'PK-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['PK2-material'].geometry}
            material={materials.material_18}
            userData={{ name: 'PK2-material' }}
          />
        </group>
        <group
          position={[-136.415, 78.439, 11.188]}
          rotation={[0, 0, 0.087]}
          scale={0.871}
          userData={{ name: 'Plane_076' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material005'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.005' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material003'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material003'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.003' }}
          />
        </group>
        <group
          position={[-150.052, 122.26, 11.188]}
          rotation={[0, 0, -0.594]}
          scale={0.871}
          userData={{ name: 'Plane_078' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material004'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.004' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material002'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material002'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.002' }}
          />
        </group>
        <group
          position={[-133.114, -105.981, 11.188]}
          rotation={[0, 0, 0.087]}
          scale={0.871}
          userData={{ name: 'Plane_079' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material003'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.003' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material001'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material.001' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material001'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material.001' }}
          />
        </group>
        <group
          position={[-129.607, -103.131, 11.188]}
          rotation={[0, 0, 1.068]}
          scale={0.871}
          userData={{ name: 'Plane_080' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['BK1-material002'].geometry}
            material={materials['material_8.001']}
            userData={{ name: 'BK1-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['OR1-material'].geometry}
            material={materials['Lamp.001_0']}
            userData={{ name: 'OR1-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['WE2-material'].geometry}
            material={materials.material_2}
            userData={{ name: 'WE2-material' }}
          />
        </group>
        <group
          position={[91.023, -112.313, 39.642]}
          rotation={[0, 0, -0.661]}
          scale={1.838}
          userData={{ name: 'Plane_081' }}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY1-material002'].geometry}
            material={materials.Lamp}
            userData={{ name: 'GY1-material.002' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY2-material'].geometry}
            material={materials.material_19}
            userData={{ name: 'GY2-material' }}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes['GY3-material'].geometry}
            material={materials.material_20}
            userData={{ name: 'GY3-material' }}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WE1-material007'].geometry}
          material={materials.material_7}
          position={[-97.224, -62.864, -1.918]}
          rotation={[-0.089, -0.295, -0.02]}
          scale={[8.561, 2.134, 16.033]}
          userData={{ name: 'WE1-material.007' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WE1-material'].geometry}
          material={materials.material_7}
          position={[-121.784, -57.552, -4.988]}
          rotation={[-2.851, -0.104, 1.512]}
          scale={[8.561, 2.134, 16.033]}
          userData={{ name: 'WE1-material' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WE1-material006'].geometry}
          material={materials.material_7}
          position={[-97.397, -72.03, -1.156]}
          scale={7.007}
          userData={{ name: 'WE1-material.006' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WE1-material008'].geometry}
          material={materials.material_7}
          position={[105.733, -62.982, -1.156]}
          scale={7.007}
          userData={{ name: 'WE1-material.008' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WE1-material004'].geometry}
          material={materials.material_7}
          position={[-123.619, 111.145, 35.396]}
          scale={7.007}
          userData={{ name: 'WE1-material.004' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['WE1-material003'].geometry}
          material={materials.material_7}
          position={[-36.903, -23.978, 48.821]}
          scale={7.007}
          userData={{ name: 'WE1-material.003' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material029'].geometry}
          material={materials.material_5}
          position={[-16.981, -25.953, 56.949]}
          rotation={[0.592, 0.37, 2.16]}
          scale={2.363}
          userData={{ name: 'G2-material.029' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material028'].geometry}
          material={materials.material_5}
          position={[-17.375, -25.354, 56.949]}
          rotation={[0.592, 0.37, 2.16]}
          scale={2.363}
          userData={{ name: 'G2-material.028' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material026'].geometry}
          material={materials.material_5}
          position={[103.824, -50.499, -6.928]}
          rotation={[0, 0, 0.47]}
          scale={0.416}
          userData={{ name: 'G2-material.026' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material027'].geometry}
          material={materials.material_5}
          position={[132.904, 6.466, 0.66]}
          rotation={[0, 0, 0.47]}
          scale={0.416}
          userData={{ name: 'G2-material.027' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material025'].geometry}
          material={materials.material_5}
          position={[134.963, -48.541, -10.762]}
          rotation={[0, 0, -1.112]}
          scale={0.416}
          userData={{ name: 'G2-material.025' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material024'].geometry}
          material={materials.material_5}
          position={[-118.589, -106.786, -14.45]}
          rotation={[0, 0, 0.47]}
          scale={0.401}
          userData={{ name: 'G2-material.024' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material023'].geometry}
          material={materials.material_5}
          position={[-123.143, -93.764, -14.45]}
          rotation={[0, 0, -1.085]}
          scale={0.401}
          userData={{ name: 'G2-material.023' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material022'].geometry}
          material={materials.material_5}
          position={[-103.267, 54.235, 0.66]}
          rotation={[0, 0, -1.085]}
          scale={0.416}
          userData={{ name: 'G2-material.022' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material021'].geometry}
          material={materials.material_5}
          position={[-117.896, 74.107, -5.878]}
          rotation={[0, 0, -1.789]}
          scale={0.416}
          userData={{ name: 'G2-material.021' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material020'].geometry}
          material={materials.material_5}
          position={[-107.298, -77.266, -11.398]}
          rotation={[0, 0, 0.47]}
          scale={0.416}
          userData={{ name: 'G2-material.020' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material019'].geometry}
          material={materials.material_5}
          position={[-135.573, -93.1, -16.947]}
          rotation={[0, 0, -0.512]}
          scale={0.416}
          userData={{ name: 'G2-material.019' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material018'].geometry}
          material={materials.material_5}
          position={[-79.99, 94.254, -5.878]}
          rotation={[0, 0, -3.096]}
          scale={0.416}
          userData={{ name: 'G2-material.018' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material017'].geometry}
          material={materials.material_5}
          position={[-95.353, 74.944, 0.66]}
          rotation={[0, 0, -2.392]}
          scale={0.416}
          userData={{ name: 'G2-material.017' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material002'].geometry}
          material={materials.material_5}
          position={[-120.98, 136.519, -20.979]}
          rotation={[0, 0, -2.392]}
          scale={0.416}
          userData={{ name: 'G2-material.002' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material001'].geometry}
          material={materials.material_5}
          position={[-120.98, 136.519, -20.979]}
          rotation={[0, 0, -2.392]}
          scale={0.416}
          userData={{ name: 'G2-material.001' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material'].geometry}
          material={materials.material_5}
          position={[-103.728, 74.944, 0.54]}
          rotation={[0, 0, -2.392]}
          scale={0.416}
          userData={{ name: 'G2-material' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material016'].geometry}
          material={materials.material_5}
          position={[54.694, -43.058, -5.047]}
          rotation={[0, 0, -2.392]}
          scale={0.416}
          userData={{ name: 'G2-material.016' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material015'].geometry}
          material={materials.material_5}
          position={[70.057, -23.748, -11.584]}
          rotation={[0, 0, -3.096]}
          scale={0.416}
          userData={{ name: 'G2-material.015' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material014'].geometry}
          material={materials.material_5}
          position={[115.405, -27.706, -6.899]}
          rotation={[0, 0, 0.47]}
          scale={0.342}
          userData={{ name: 'G2-material.014' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material013'].geometry}
          material={materials.material_5}
          position={[118.943, -30.382, -6.899]}
          rotation={[0, 0, -1.217]}
          scale={0.342}
          userData={{ name: 'G2-material.013' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material012'].geometry}
          material={materials.material_5}
          position={[-24.645, 21.028, 41.115]}
          rotation={[1.187, 0.363, 2.499]}
          scale={2.363}
          userData={{ name: 'G2-material.012' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material011'].geometry}
          material={materials['material_5.001']}
          position={[-14.683, -41.14, 37.792]}
          rotation={[-1.755, 0.511, 0.236]}
          scale={2.363}
          userData={{ name: 'G2-material.011' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material006'].geometry}
          material={materials.material_5}
          position={[-138.981, 96.076, -11.993]}
          rotation={[0, 0, -1.789]}
          scale={0.416}
          userData={{ name: 'G2-material.006' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material005'].geometry}
          material={materials.material_5}
          position={[-114.36, 126.125, -16.262]}
          rotation={[0, 0, -1.789]}
          scale={0.416}
          userData={{ name: 'G2-material.005' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material004'].geometry}
          material={materials.material_5}
          position={[93.993, -68.862, -5.047]}
          rotation={[0, 0, 2.373]}
          scale={0.416}
          userData={{ name: 'G2-material.004' }}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['G2-material003'].geometry}
          material={materials.material_5}
          position={[122.668, -81.189, -8.129]}
          rotation={[0, 0, -0.615]}
          scale={0.416}
          userData={{ name: 'G2-material.003' }}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/island1.glb')
